# 21

In [1]:
import pandas as pd

1 Create a data frame from the file nyc-parking-violations-2020.csv. We are only interested in a handful of the columns:
- Date First Observed
- Plate ID
- Registration State
- Issue Date (a string in MM/DD/YYYY format, always followed by 12:00:00
- Vehicle Make
- Street Name
- Vehicle Color

In [2]:
nyc_pv = pd.read_csv('./data/nyc-parking-violations-2020.csv',
                    usecols=['Date First Observed','Plate ID', 'Registration State', 'Issue Date', 'Vehicle Make', 'Street Name', 'Vehicle Color'])

Set the data frame’s index to the Issue Date column.

In [3]:
df = nyc_pv.set_index('Issue Date')

Determine what three makes were most frequently ticketed on January 2, 2020

In [4]:
df.loc['01/02/2020 12:00:00 AM', 'Vehicle Make'].value_counts().head(3)

Vehicle Make
TOYOT    3829
HONDA    3593
FORD     3164
Name: count, dtype: int64

Determine the five streets on which cars got the most tickets on June 1, 2020.

In [5]:
df.loc['06/01/2020 12:00:00 AM', 'Street Name'].value_counts().head(5)

Street Name
WB CONDUIT BLVD @ LI    1068
SB WEST ST @ LEROY S     335
EB HORACE HARDING EX     273
EB QUEENS BLVD @ 82N     245
WB ATLANTIC AVE @ CL     229
Name: count, dtype: int64

Set the index to `Vehicle Color`.

In [6]:
df = df.reset_index().set_index('Vehicle Color')

Determine the most common make of vehicles that were either red or blue

In [7]:
(df.loc[['BLUE', 'RED'], 'Vehicle Make'].value_counts().head(1))

Vehicle Make
HONDA    39353
Name: count, dtype: int64

What three car makes were most often ticketed from January 2 through January 10?

In [8]:
df = df.reset_index()   # undo the setting of the index from the previous cell

# let's do it in chained format:

(
    df
    .set_index('Issue Date')
    .sort_index()
    .loc['01/02/2020 12:00:00 AM':'01/10/2020 23:59:59 PM',
         'Vehicle Make']
    .value_counts()
    .head(3)
)

Vehicle Make
FORD     38958
TOYOT    37096
HONDA    35962
Name: count, dtype: int64

How many tickets did the second-most-ticketed car get in 2020?

In [9]:
df = df.reset_index()
df['Plate ID'].value_counts().head(2)

Plate ID
BLANKPLATE    8882
2704819       1535
Name: count, dtype: int64

What state was that car from?

In [10]:
df = df.set_index('Plate ID')
df.loc['2704819', 'Registration State']

Plate ID
2704819    IN
2704819    IN
2704819    IN
2704819    IN
2704819    IN
           ..
2704819    IN
2704819    IN
2704819    IN
2704819    IN
2704819    IN
Name: Registration State, Length: 1535, dtype: object

Was it always ticketed in the same location?

In [11]:
df.loc['2704819', 'Street Name'].value_counts()

Street Name
8th Ave                 395
Penn Plz                230
7th Ave                  92
9th Ave                  63
Broadway                 57
                       ...
WEST 36 STREET            1
N/S W 25 ST               1
AVENUE OF THE AMERIC      1
WEST 41 ST                1
N/S W 31 ST               1
Name: count, Length: 113, dtype: int64

# 22

Read in the scores file, only keeping the `Year`, `State.Code`, `Total.Math`, `Total.Test-takers`, and `Total.Verbal` columns.

In [12]:
sat_scores = pd.read_csv('./data/sat-scores.csv',
                         usecols= ['Year', 'State.Code', 'Total.Math', 'Total.Test-takers', 'Total.Verbal'])

Create a multi-index based on the year and the two-letter state code.

In [13]:
df = sat_scores.set_index(['Year', 'State.Code'])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 577 entries, (np.int64(2005), 'AL') to (np.int64(2015), 'WY')
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Total.Math         577 non-null    int64
 1   Total.Test-takers  577 non-null    int64
 2   Total.Verbal       577 non-null    int64
dtypes: int64(3)
memory usage: 17.6+ KB

Determine how many people took the SAT in 2005.

In [15]:
df.loc[2005, 'Total.Test-takers'].sum()

np.int64(1344824)

Determine the average SAT math score in 2010 from New York (NY), New Jersey (NJ), Massachusetts (MA), and Illinois (IL).

In [16]:
df.loc[(2010, ['NY', 'NJ', 'MA', 'IL']), 'Total.Math'].mean()

np.float64(535.25)

Determine the average SAT verbal score in 2012–2015 from Arizona (AZ), California (CA), and Texas (TX).

In [17]:
df.loc[([2012,2013,2014,2015], ['AZ', 'CA', 'TX']), 'Total.Verbal'].mean()

np.float64(497.3333333333333)

# 23

Read the data file (`olympic_athlete_events.csv`) into a data frame, keep these columns: `Age`, `Height`, `Team`, `Year`, `Season`, `City`, `Sport`,
`Event`, and `Medal`.

The multi-index should be based on `Year`, `Season`, `Sport`, and `Event`.

In [18]:
olympic_athlete_events = pd.read_csv('./data/olympic_athlete_events.csv',
                                     usecols=['Age', 'Height', 'Team', 'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'],
                                     index_col= ['Year', 'Season', 'Sport', 'Event'])

In [19]:
olympic_athlete_events.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 271116 entries, (np.int64(1992), 'Summer', 'Basketball', "Basketball Men's Basketball") to (np.int64(2002), 'Winter', 'Bobsleigh', "Bobsleigh Men's Four")
Data columns (total 5 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Age     261642 non-null  float64
 1   Height  210945 non-null  float64
 2   Team    271116 non-null  object
 3   City    271116 non-null  object
 4   Medal   39783 non-null   object
dtypes: float64(2), object(3)
memory usage: 11.7+ MB

In [20]:
df = olympic_athlete_events.sort_index()
df.head()

                                                     Age  Height  \
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  24.0     NaN
                      Athletics Men's 1,500 metres   NaN     NaN
                      Athletics Men's 1,500 metres  22.0     NaN
                      Athletics Men's 1,500 metres  23.0   154.0
                      Athletics Men's 1,500 metres  21.0     NaN

                                                             Team    City  \
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  United States  Athina
                      Athletics Men's 1,500 metres         Greece  Athina
                      Athletics Men's 1,500 metres      Australia  Athina
                      Athletics Men's 1,500 metres        Germany  Athina
                      Athletics Men's 1,500 metres         Greece  Athina

                                                     Medal
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  Silver
                      Athletics Men's 1,500 metres     NaN
                      Athletics Men's 1,500 metres    Gold
                      Athletics Men's 1,500 metres     NaN
                      Athletics Men's 1,500 metres     NaN

What is the average age of the competing athletes in summer games held between 1936 and 2000?

In [21]:
df.loc[(slice(1936,2000), 'Summer'), 'Age'].mean()

np.float64(25.026883940421765)

Which team won the most medals in all archery events?

In [22]:
df.dropna(subset='Medal').loc[(slice(None), 'Summer', 'Archery'), 'Team'].value_counts()

Team
South Korea           69
Belgium               52
France                48
United States         41
China                 19
Italy                 15
Great Britain         13
Chinese Taipei         9
Netherlands            9
Ukraine                8
Cincinnati Archers     8
Japan                  7
Germany                7
Soviet Union           7
Finland                6
Australia              5
Boston Archers         4
Unified Team           4
Potomac Archers        4
Russia                 4
Poland                 4
Spain                  3
Indonesia              3
Sweden                 2
Mexico                 2
Name: count, dtype: int64

Starting in 1980, what is the average height of the “Table Tennis Women’s Team” event?

In [23]:
df.loc[(slice(1980, None), 'Summer', slice(None), 'Table Tennis Women\'s Team'), 'Height'].mean()

np.float64(165.04827586206898)

Starting in 1980, what is the average height of both “Table Tennis Women’s Team” and “Table Tennis Men’s Team”?

In [24]:
df.loc[(slice(1980, None), 'Summer', slice(None), ['Table Tennis Men\'s Team', 'Table Tennis Women\'s Team']), 'Height'].mean()

np.float64(171.26643598615917)

Using `xs`, we can shorten that query to:

In [25]:
df.xs('Table Tennis Women\'s Team', level='Event')['Height'].mean()
# if we didn't know the season, we could use:
# df.xs(('Summer', 'Table Tennis Women\'s Team'), level=['Season', 'Event'])['Height'].mean()

np.float64(165.04827586206898)

A more general way to retrieve from a multi-index is `IndexSlice`.

In [26]:
from pandas import IndexSlice as idx

In [27]:
df.loc[idx[1980:2016, :, 'Swimming':'Table tennis'], :]

                                                                 Age  Height  \
Year Season Sport        Event
1980 Summer Swimming     Swimming Men's 1,500 metres Freestyle  19.0   185.0
                         Swimming Men's 1,500 metres Freestyle  18.0   181.0
                         Swimming Men's 1,500 metres Freestyle  19.0   178.0
                         Swimming Men's 1,500 metres Freestyle  21.0   184.0
                         Swimming Men's 1,500 metres Freestyle  16.0   174.0
...                                                              ...     ...
2016 Summer Table Tennis Table Tennis Women's Team              26.0   166.0
                         Table Tennis Women's Team              20.0   166.0
                         Table Tennis Women's Team              25.0   162.0
                         Table Tennis Women's Team              28.0   165.0
                         Table Tennis Women's Team              22.0   168.0

                                                                         Team  \
Year Season Sport        Event
1980 Summer Swimming     Swimming Men's 1,500 metres Freestyle  Great Britain
                         Swimming Men's 1,500 metres Freestyle   Soviet Union
                         Swimming Men's 1,500 metres Freestyle          Spain
                         Swimming Men's 1,500 metres Freestyle  Great Britain
                         Swimming Men's 1,500 metres Freestyle         Brazil
...                                                                       ...
2016 Summer Table Tennis Table Tennis Women's Team                  Singapore
                         Table Tennis Women's Team              United States
                         Table Tennis Women's Team                  Australia
                         Table Tennis Women's Team              United States
                         Table Tennis Women's Team                  Singapore

                                                                          City  \
Year Season Sport        Event
1980 Summer Swimming     Swimming Men's 1,500 metres Freestyle          Moskva
                         Swimming Men's 1,500 metres Freestyle          Moskva
                         Swimming Men's 1,500 metres Freestyle          Moskva
                         Swimming Men's 1,500 metres Freestyle          Moskva
                         Swimming Men's 1,500 metres Freestyle          Moskva
...                                                                        ...
2016 Summer Table Tennis Table Tennis Women's Team              Rio de Janeiro
                         Table Tennis Women's Team              Rio de Janeiro
                         Table Tennis Women's Team              Rio de Janeiro
                         Table Tennis Women's Team              Rio de Janeiro
                         Table Tennis Women's Team              Rio de Janeiro

                                                                 Medal
Year Season Sport        Event
1980 Summer Swimming     Swimming Men's 1,500 metres Freestyle     NaN
                         Swimming Men's 1,500 metres Freestyle  Silver
                         Swimming Men's 1,500 metres Freestyle     NaN
                         Swimming Men's 1,500 metres Freestyle     NaN
                         Swimming Men's 1,500 metres Freestyle     NaN
...                                                                ...
2016 Summer Table Tennis Table Tennis Women's Team                 NaN
                         Table Tennis Women's Team                 NaN
                         Table Tennis Women's Team                 NaN
                         Table Tennis Women's Team                 NaN
                         Table Tennis Women's Team                 NaN

[17935 rows x 5 columns]

How tall was the tallest-ever tennis player in Olympic games from 1980 until 2016?

Since Tennis is a summer sport, let's remove `Season` from the index.

In [28]:
df = df.reset_index('Season')

In [29]:
df.loc[(slice(1980,2020), 'Tennis'), 'Height'].max()

np.float64(208.0)

In which city were the most gold medals awarded from 1980 onward?

In [30]:
df.loc[1980:].loc[lambda df_: df_['Medal'] == 'Gold', 'City'].value_counts()

City
Beijing           671
Rio de Janeiro    665
Athina            664
Sydney            663
London            632
Atlanta           608
Barcelona         559
Seoul             520
Los Angeles       497
Moskva            457
Sochi             202
Torino            176
Vancouver         174
Salt Lake City    162
Nagano            145
Lillehammer       110
Albertville       104
Calgary            87
Sarajevo           74
Lake Placid        72
Name: count, dtype: int64

How many gold medals were received by the United States since 1980?

In [31]:
df.loc[1980:].loc[lambda df_: (df_['Team'] == 'United States') & (df_['Medal'] == 'Gold'), 'City'].count()

np.int64(1257)

# 24

Read in our Olympic data again.
- Only use these columns: `Age`, `Height`, `Team`, `Year`, `Season`, `Sport`, `Medal`.
- Only include games from 1980 to the present.
- Only include data from these countries: Great Britain, France, United States, Switzerland, China, and India

In [32]:
df = olympic_athlete_events.reset_index()[['Age', 'Height', 'Team', 'Year', 'Season', 'Sport', 'Medal']]
df = df.loc[df['Team'].isin(['Great Britain', 'France', 'United States', 'Switzerland', 'China', 'India'])]
df = df.loc[df['Year'] >= 1980]

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27893 entries, 0 to 271037
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     27879 non-null  float64
 1   Height  27350 non-null  float64
 2   Team    27893 non-null  object
 3   Year    27893 non-null  int64
 4   Season  27893 non-null  object
 5   Sport   27893 non-null  object
 6   Medal   5256 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 1.7+ MB

What was the average age of Olympic athletes? In which country do players appear to consistently be the youngest?

In [34]:
df.pivot_table(index='Year', columns='Team', values='Age')

Team,China,France,Great Britain,India,Switzerland,United States
Year,,,,,,
1980,21.868421,23.524590,22.882507,25.506667,24.557823,22.770992
1984,22.076336,24.369830,24.445423,24.905660,23.589744,24.437118
1988,22.358447,24.520076,25.439560,24.000000,26.218868,24.904977
1992,21.955752,25.140187,25.584055,24.184615,25.413194,25.474866
1994,20.627907,24.601307,25.282051,NaN,25.500000,24.976744
1996,22.021531,25.296629,26.746032,24.629630,27.122093,26.273277
1998,21.784091,25.462069,27.243902,16.000000,25.641509,25.146154
2000,22.515306,25.982833,26.406948,25.400000,27.376812,26.576203
2002,23.127451,25.737805,26.833333,20.000000,26.238710,25.726316
2004,23.006122,26.139073,26.303977,24.728395,27.343284,26.439093
2006,23.457143,26.303226,26.851852,25.200000,26.284848,25.637288
2008,23.903955,26.285714,25.200969,25.402985,27.312500,26.225806
2010,23.239669,25.911458,26.147059,25.666667,26.548387,25.841584
2012,23.894168,26.606635,25.922619,25.637363,27.172131,26.461883
2014,23.400000,25.708995,25.628571,25.000000,25.855814,26.189189
2016,23.873706,27.095238,26.653191,26.100000,25.891892,26.217454

How tall were the tallest athletes in each sport in each year?

In [37]:
df.pivot_table(
    index='Sport',
    columns='Year',
    values='Height',
    aggfunc='max'
)

Year,1980,1984,1988,1992,1994,1996,1998,2000,2002,2004,2006,2008,2010,2012,2014,2016
Sport,,,,,,,,,,,,,,,,
Alpine Skiing,184.0,184.0,185.0,185.0,188.0,NaN,188.0,NaN,189.0,NaN,193.0,NaN,193.0,NaN,200.0,NaN
Archery,185.0,188.0,188.0,191.0,NaN,191.0,NaN,191.0,NaN,193.0,NaN,193.0,NaN,193.0,NaN,188.0
Athletics,197.0,203.0,203.0,200.0,NaN,198.0,NaN,197.0,NaN,203.0,NaN,203.0,NaN,208.0,NaN,203.0
Badminton,NaN,NaN,NaN,186.0,NaN,189.0,NaN,187.0,NaN,190.0,NaN,190.0,NaN,191.0,NaN,191.0
Baseball,NaN,NaN,NaN,198.0,NaN,195.0,NaN,206.0,NaN,NaN,NaN,198.0,NaN,NaN,NaN,NaN
Basketball,196.0,216.0,216.0,216.0,NaN,216.0,NaN,226.0,NaN,226.0,NaN,226.0,NaN,221.0,NaN,218.0
Beach Volleyball,NaN,NaN,NaN,NaN,NaN,193.0,NaN,195.0,NaN,192.0,NaN,202.0,NaN,202.0,NaN,188.0
Biathlon,190.0,190.0,188.0,192.0,192.0,NaN,192.0,NaN,192.0,NaN,193.0,NaN,193.0,NaN,193.0,NaN
Bobsleigh,NaN,184.0,NaN,NaN,NaN,NaN,198.0,NaN,190.0,NaN,193.0,NaN,191.0,NaN,189.0,NaN
Boxing,190.0,195.0,196.0,193.0,NaN,191.0,NaN,198.0,NaN,190.0,NaN,203.0,NaN,201.0,NaN,200.0
Canoeing,203.0,203.0,203.0,203.0,NaN,205.0,NaN,203.0,NaN,190.0,NaN,200.0,NaN,194.0,NaN,191.0
Cross Country Skiing,185.0,189.0,186.0,190.0,190.0,NaN,185.0,NaN,188.0,NaN,188.0,NaN,193.0,NaN,193.0,NaN
Curling,NaN,NaN,NaN,NaN,NaN,NaN,188.0,NaN,193.0,NaN,183.0,NaN,189.0,NaN,192.0,NaN
Cycling,190.0,190.0,195.0,192.0,NaN,189.0,NaN,192.0,NaN,192.0,NaN,196.0,NaN,198.0,NaN,196.0
Diving,176.0,175.0,178.0,183.0,NaN,183.0,NaN,183.0,NaN,182.0,NaN,185.0,NaN,178.0,NaN,188.0
Equestrianism,179.0,187.0,187.0,184.0,NaN,196.0,NaN,187.0,NaN,196.0,NaN,196.0,NaN,196.0,NaN,196.0
Fencing,193.0,208.0,208.0,193.0,NaN,196.0,NaN,196.0,NaN,196.0,NaN,196.0,NaN,197.0,NaN,197.0
Figure Skating,183.0,182.0,180.0,182.0,182.0,NaN,182.0,NaN,183.0,NaN,188.0,NaN,188.0,NaN,193.0,NaN
Football,NaN,188.0,190.0,193.0,NaN,191.0,NaN,193.0,NaN,180.0,NaN,193.0,NaN,195.0,NaN,188.0
Freestyle Skiing,NaN,NaN,NaN,190.0,186.0,NaN,193.0,NaN,193.0,NaN,183.0,NaN,193.0,NaN,188.0,NaN
Golf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193.0
Gymnastics,180.0,179.0,181.0,178.0,NaN,180.0,NaN,175.0,NaN,176.0,NaN,184.0,NaN,184.0,NaN,184.0
Handball,197.0,200.0,200.0,198.0,NaN,203.0,NaN,199.0,NaN,199.0,NaN,201.0,NaN,204.0,NaN,202.0
Hockey,179.0,190.0,189.0,193.0,NaN,196.0,NaN,196.0,NaN,196.0,NaN,189.0,NaN,189.0,NaN,193.0
Ice Hockey,193.0,193.0,195.0,194.0,195.0,NaN,195.0,NaN,190.0,NaN,195.0,NaN,196.0,NaN,198.0,NaN
Judo,196.0,204.0,204.0,196.0,NaN,205.0,NaN,202.0,NaN,202.0,NaN,203.0,NaN,203.0,NaN,203.0
Luge,188.0,188.0,183.0,188.0,188.0,NaN,188.0,NaN,185.0,NaN,188.0,NaN,188.0,NaN,188.0,NaN
Modern Pentathlon,185.0,188.0,190.0,190.0,NaN,185.0,NaN,186.0,NaN,191.0,NaN,188.0,NaN,188.0,NaN,194.0
Nordic Combined,193.0,183.0,193.0,183.0,180.0,NaN,181.0,NaN,183.0,NaN,183.0,NaN,190.0,NaN,190.0,NaN
Rhythmic Gymnastics,NaN,172.0,170.0,172.0,NaN,172.0,NaN,173.0,NaN,178.0,NaN,177.0,NaN,173.0,NaN,177.0
Rowing,198.0,205.0,205.0,205.0,NaN,205.0,NaN,204.0,NaN,207.0,NaN,207.0,NaN,206.0,NaN,207.0
Rugby Sevens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,195.0
Sailing,186.0,198.0,198.0,195.0,NaN,203.0,NaN,201.0,NaN,198.0,NaN,194.0,NaN,195.0,NaN,197.0
Shooting,183.0,189.0,190.0,190.0,NaN,195.0,NaN,188.0,NaN,192.0,NaN,192.0,NaN,198.0,NaN,200.0
Short Track Speed Skating,NaN,NaN,NaN,182.0,183.0,NaN,183.0,NaN,188.0,NaN,186.0,NaN,186.0,NaN,189.0,NaN
Skeleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.0,NaN,185.0,NaN,185.0,NaN,190.0,NaN
Ski Jumping,185.0,180.0,185.0,190.0,185.0,NaN,185.0,NaN,185.0,NaN,190.0,NaN,190.0,NaN,190.0,NaN
Snowboarding,NaN,NaN,NaN,NaN,NaN,NaN,190.0,NaN,190.0,NaN,186.0,NaN,190.0,NaN,188.0,NaN
Softball,NaN,NaN,NaN,NaN,NaN,182.0,NaN,185.0,NaN,188.0,NaN,191.0,NaN,NaN,NaN,NaN
Speed Skating,185.0,190.0,193.0,193.0,186.0,NaN,186.0,NaN,193.0,NaN,188.0,NaN,203.0,NaN,193.0,NaN
Swimming,194.0,200.0,200.0,201.0,NaN,201.0,NaN,201.0,NaN,202.0,NaN,203.0,NaN,203.0,NaN,206.0
Synchronized Swimming,NaN,178.0,180.0,180.0,NaN,181.0,NaN,181.0,NaN,177.0,NaN,175.0,NaN,178.0,NaN,177.0
Table Tennis,NaN,NaN,185.0,193.0,NaN,193.0,NaN,188.0,NaN,193.0,NaN,192.0,NaN,188.0,NaN,186.0
Taekwondo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,198.0,NaN,198.0,NaN,201.0,NaN,201.0,NaN,197.0
Tennis,NaN,NaN,193.0,200.0,NaN,200.0,NaN,198.0,NaN,188.0,NaN,198.0,NaN,206.0,NaN,196.0
Trampolining,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175.0,NaN,172.0,NaN,179.0,NaN,179.0,NaN,178.0
Triathlon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,192.0,NaN,191.0,NaN,196.0,NaN,191.0,NaN,191.0
Volleyball,NaN,203.0,203.0,202.0,NaN,203.0,NaN,204.0,NaN,209.0,NaN,210.0,NaN,206.0,NaN,209.0
Water Polo,NaN,198.0,205.0,205.0,NaN,200.0,NaN,200.0,NaN,203.0,NaN,201.0,NaN,203.0,NaN,206.0
Weightlifting,180.0,188.0,190.0,190.0,NaN,195.0,NaN,182.0,NaN,180.0,NaN,177.0,NaN,189.0,NaN,187.0
Wrestling,205.0,190.0,193.0,193.0,NaN,194.0,NaN,196.0,NaN,195.0,NaN,203.0,NaN,203.0,NaN,188.0

How many medals did each country earn each year?

In [40]:
pd.pivot_table(df.dropna(subset='Medal'),
               index='Year',
               columns='Team',
               values='Medal',
               aggfunc='size'
               )

Team  China  France  Great Britain  India  Switzerland  United States
Year
1980    NaN    30.0           48.0   16.0          5.0           30.0
1984   74.0    70.0           71.0    NaN         17.0          359.0
1988   50.0    31.0           54.0    NaN         24.0          212.0
1992   73.0    65.0           50.0    NaN          2.0          236.0
1994    3.0    11.0            3.0    NaN          8.0           19.0
1996   94.0    49.0           26.0    1.0         11.0          255.0
1998   14.0    13.0            4.0    NaN         10.0           30.0
2000   65.0    64.0           52.0    1.0         14.0          240.0
2002   14.0    13.0            6.0    NaN         20.0           70.0
2004   82.0    53.0           55.0    1.0          5.0          259.0
2006    9.0    15.0            1.0    NaN         15.0           48.0
2008  170.0    77.0           81.0    3.0         11.0          309.0
2010   15.0    14.0            1.0    NaN         12.0           89.0
2012  117.0    78.0          122.0    6.0          4.0          238.0
2014   12.0    18.0           10.0    NaN         28.0           52.0
2016  109.0    96.0          145.0    2.0         11.0          256.0

Create a pivot table that shows the number of medals each team won per year, with the index including the year and the season in which the games took place.

In [42]:
df.pivot_table(
    index=['Year', 'Season'],
    columns='Team',
    values='Medal',
    aggfunc='size',
)

Team         China  France  Great Britain  India  Switzerland  United States
Year Season
1980 Summer    NaN   200.0          328.0   78.0         86.0            NaN
     Winter   38.0    44.0           56.0    NaN         61.0          131.0
1984 Summer  323.0   354.0          509.0   53.0        245.0          693.0
     Winter   70.0    57.0           60.0    NaN         67.0          128.0
1988 Summer  423.0   413.0          468.0   55.0        151.0          715.0
     Winter   15.0   111.0           79.0    3.0        114.0          171.0
1992 Summer  378.0   476.0          500.0   61.0        171.0          728.0
     Winter   74.0   166.0           78.0    4.0        117.0          208.0
1994 Winter   43.0   153.0           39.0    NaN         94.0          215.0
1996 Summer  418.0   445.0          379.0   54.0        172.0          827.0
1998 Winter   88.0   145.0           41.0    1.0        106.0          260.0
2000 Summer  392.0   466.0          403.0   70.0        138.0          748.0
2002 Winter  102.0   164.0           54.0    1.0        155.0          285.0
2004 Summer  490.0   453.0          352.0   81.0        134.0          706.0
2006 Winter  140.0   155.0           54.0    5.0        165.0          295.0
2008 Summer  708.0   441.0          413.0   67.0        112.0          744.0
2010 Winter  121.0   192.0           68.0    3.0        186.0          303.0
2012 Summer  463.0   422.0          672.0   91.0        122.0          669.0
2014 Winter  105.0   189.0           70.0    2.0        215.0          333.0
2016 Summer  483.0   504.0          470.0  130.0        148.0          699.0

Create a pivot table that shows both the average age and the average height per year per team.

In [49]:
pd.pivot_table(df,
               index='Year',
               columns='Team',
               values=['Age', 'Height'],
               aggfunc='max')

       Age                                                      Height         \
Team China France Great Britain India Switzerland United States  China France
Year
1980  32.0   34.0          37.0  56.0        47.0          32.0  170.0  203.0
1984  30.0   50.0          47.0  45.0        52.0          49.0  216.0  214.0
1988  34.0   43.0          55.0  36.0        47.0          52.0  210.0  203.0
1992  35.0   47.0          48.0  38.0        53.0          54.0  215.0  203.0
1994  29.0   33.0          36.0   NaN        35.0          36.0  181.0  195.0
1996  39.0   53.0          48.0  46.0        49.0          50.0  215.0  201.0
1998  29.0   34.0          36.0  16.0        37.0          40.0  185.0  198.0
2000  39.0   46.0          52.0  38.0        53.0          46.0  226.0  218.0
2002  30.0   38.0          40.0  20.0        36.0          48.0  188.0  190.0
2004  43.0   50.0          48.0  43.0        55.0          52.0  226.0  202.0
2006  32.0   38.0          40.0  29.0        42.0          44.0  188.0  190.0
2008  45.0   51.0          53.0  42.0        45.0          58.0  226.0  203.0
2010  34.0   38.0          45.0  28.0        41.0          40.0  194.0  191.0
2012  41.0   49.0          56.0  39.0        49.0          54.0  221.0  208.0
2014  32.0   37.0          41.0  30.0        42.0          45.0  193.0  191.0
2016  38.0   53.0          60.0  43.0        50.0          52.0  218.0  215.0


Team Great Britain  India Switzerland United States
Year
1980         205.0  196.0       197.0         193.0
1984         203.0  188.0       204.0         213.0
1988         205.0  193.0       204.0         216.0
1992         205.0  188.0       200.0         216.0
1994         185.0    NaN       192.0         193.0
1996         205.0  191.0       200.0         216.0
1998         185.0  183.0       192.0         195.0
2000         204.0  195.0       197.0         207.0
2002         193.0  183.0       192.0         193.0
2004         207.0  195.0       197.0         213.0
2006         193.0  183.0       193.0         195.0
2008         207.0  192.0       197.0         211.0
2010         193.0  183.0       203.0         193.0
2012         211.0  196.0       198.0         216.0
2014         193.0  173.0       200.0         196.0
2016         207.0  200.0       194.0         211.0

Create a pivot table that shows the average age and the average height per year, per team, broken up by year and season.

In [50]:
pd.pivot_table(df,
               index=['Year', 'Season'],
               columns='Team',
               values=['Age', 'Height'],
               aggfunc='max')

              Age                                                      Height  \
Team        China France Great Britain India Switzerland United States  China
Year Season
1980 Summer   NaN   34.0          37.0  56.0        47.0           NaN    NaN
     Winter  32.0   29.0          36.0   NaN        33.0          32.0  170.0
1984 Summer  30.0   50.0          47.0  45.0        52.0          49.0  216.0
     Winter  28.0   36.0          34.0   NaN        30.0          34.0  176.0
1988 Summer  34.0   43.0          55.0  36.0        47.0          52.0  210.0
     Winter  24.0   39.0          29.0  24.0        34.0          39.0  181.0
1992 Summer  35.0   47.0          48.0  38.0        53.0          54.0  215.0
     Winter  29.0   32.0          30.0  21.0        32.0          36.0  181.0
1994 Winter  29.0   33.0          36.0   NaN        35.0          36.0  181.0
1996 Summer  39.0   53.0          48.0  46.0        49.0          50.0  215.0
1998 Winter  29.0   34.0          36.0  16.0        37.0          40.0  185.0
2000 Summer  39.0   46.0          52.0  38.0        53.0          46.0  226.0
2002 Winter  30.0   38.0          40.0  20.0        36.0          48.0  188.0
2004 Summer  43.0   50.0          48.0  43.0        55.0          52.0  226.0
2006 Winter  32.0   38.0          40.0  29.0        42.0          44.0  188.0
2008 Summer  45.0   51.0          53.0  42.0        45.0          58.0  226.0
2010 Winter  34.0   38.0          45.0  28.0        41.0          40.0  194.0
2012 Summer  41.0   49.0          56.0  39.0        49.0          54.0  221.0
2014 Winter  32.0   37.0          41.0  30.0        42.0          45.0  193.0
2016 Summer  38.0   53.0          60.0  43.0        50.0          52.0  218.0


Team        France Great Britain  India Switzerland United States
Year Season
1980 Summer  203.0         205.0  196.0       197.0           NaN
     Winter  185.0         183.0    NaN       186.0         193.0
1984 Summer  214.0         203.0  188.0       204.0         213.0
     Winter  185.0         189.0    NaN       184.0         193.0
1988 Summer  203.0         205.0  193.0       204.0         216.0
     Winter  195.0         186.0    NaN       189.0         193.0
1992 Summer  203.0         205.0  188.0       200.0         216.0
     Winter  194.0         184.0    NaN       192.0         193.0
1994 Winter  195.0         185.0    NaN       192.0         193.0
1996 Summer  201.0         205.0  191.0       200.0         216.0
1998 Winter  198.0         185.0  183.0       192.0         195.0
2000 Summer  218.0         204.0  195.0       197.0         207.0
2002 Winter  190.0         193.0  183.0       192.0         193.0
2004 Summer  202.0         207.0  195.0       197.0         213.0
2006 Winter  190.0         193.0  183.0       193.0         195.0
2008 Summer  203.0         207.0  192.0       197.0         211.0
2010 Winter  191.0         193.0  183.0       203.0         193.0
2012 Summer  208.0         211.0  196.0       198.0         216.0
2014 Winter  191.0         193.0  173.0       200.0         196.0
2016 Summer  215.0         207.0  200.0       194.0         211.0