# 29

Load the CSV file `nyc_taxi_2019-01.csv` into a data frame using only the columns `passenger_count`, `trip_distance`, and `total_amount`

In [65]:
import pandas as pd

In [66]:
df = pd.read_csv('./data/nyc_taxi_2019-01.csv', usecols=['passenger_count', 'trip_distance', 'total_amount'])

Using a *descending* sort, find the average cost of the 20 longest (in distance) taxi
rides in January 2019.

In [67]:
df.sort_values(by='trip_distance', ascending=False).head(20).mean().round(2)

passenger_count      1.65
trip_distance      204.63
total_amount       290.01
dtype: float64

In [68]:
df.sort_values('trip_distance', ascending=False)['total_amount'].iloc[:20].mean().round(2)

np.float64(290.01)

In [69]:
df.sort_values(by='trip_distance', ascending=False)['total_amount'].head(20).mean().round(2)

np.float64(290.01)

Using an *ascending* sort, find the average cost of the 20 longest (in distance) taxi
rides in January 2019.

In [70]:
df.sort_values('trip_distance')['total_amount'].iloc[-20:].mean().round(2)

np.float64(290.01)

In [71]:
df.sort_values(by='trip_distance')['total_amount'].tail(20).mean().round(2)

np.float64(290.01)

Sort by ascending passenger count and descending trip distance. What is the average price paid for the top 50 rides?

In [72]:
(df.sort_values(['passenger_count', 'trip_distance'], ascending=[True, False])['total_amount'].head(50).mean().round(2))

np.float64(135.5)

In [73]:
(df.sort_values(['passenger_count', 'trip_distance'], ascending=[True, False])['total_amount'].iloc[:50].mean().round(2))

np.float64(135.5)

In which five rides did people pay the most per mile? How far did people go on
those trips?

In [74]:
df = df[df['trip_distance'] != 0]
df['cost_per_mile'] = df['total_amount'] / df['trip_distance']
df['cost_per_mile'] = df['cost_per_mile'].round(2)

In [75]:
df.sort_values('cost_per_mile').tail(5).round(2)

         passenger_count  trip_distance  total_amount  cost_per_mile
4136499                1           0.01        273.96       27396.00
6403254                1           0.01        322.30       32230.00
7099014                4           0.01        415.30       41530.00
478791                 1           0.10       6667.45       66674.50
2499600                1           2.40     623261.66      259692.36

Let’s assume that multipassenger rides are split evenly among the passengers.
Given that assumption, in which 10 multipassenger rides did each individual
pay the greatest amount?

In [76]:
df = df[df['passenger_count'] >= 2]
df['payment_per_person'] = df['total_amount'] / df['passenger_count']
df.sort_values('payment_per_person').tail(10)

,passenger_count,trip_distance,total_amount,cost_per_mile,payment_per_person
5031491,2,64.30,343.32,5.34,171.66
4563340,2,0.40,350.30,875.75,175.15
4202883,2,60.23,369.06,6.13,184.53
4751745,2,100.78,403.50,4.00,201.75
5726185,2,65.05,416.82,6.41,208.41
149362,2,17.20,426.80,24.81,213.40
7593395,2,83.61,449.32,5.37,224.66
3842620,2,110.04,515.82,4.69,257.91
3014027,2,16.60,560.76,33.78,280.38
2972145,2,19.90,589.96,29.65,294.98

Using `ignore_index=True`, find the mean `total_amount` of the 20 longest rides:

In [78]:
df.sort_values('trip_distance',
               ascending=False,
                ignore_index=True)['total_amount'].loc[:20].mean().round(2)

np.float64(253.66)

# 30

Load taxi data from January 2019 into a data frame using only the columns
`passenger_count`, `trip_distance`, and `total_amount`.

In [88]:
df = pd.read_csv('./data/nyc_taxi_2019-01.csv', usecols=['passenger_count', 'trip_distance', 'total_amount'])

For each number of passengers, find the mean cost of a taxi ride. Sort this
result from lowest (i.e., cheapest) to highest (i.e., most expensive).

In [94]:
df.groupby('passenger_count')['total_amount'].mean().round(2).sort_values()

passenger_count
6    15.44
5    15.55
3    15.60
1    15.61
4    15.65
2    15.83
0    18.66
9    31.09
7    48.28
8    64.11
Name: total_amount, dtype: float64

Sort the results again by increasing the number of passengers.

In [105]:
df.groupby('passenger_count')['total_amount'].mean().round(2).sort_index()

passenger_count
0    18.66
1    15.61
2    15.83
3    15.60
4    15.65
5    15.55
6    15.44
7    48.28
8    64.11
9    31.09
Name: total_amount, dtype: float64

Create a new column, `trip_distance_group`, in which the values are short (< 2
miles), medium ($\geq$ 2 miles and $\leq$ 10 miles), and long (> 10 miles). What is the
average number of passengers per trip length category? Sort this result from highest (most passengers) to lowest (fewest passengers).

In [104]:
df['trip_distance_group'] = pd.cut(df['trip_distance'],
                                   [df['trip_distance'].min(), 2, 10,
                                    df['trip_distance'].max()],
                                  labels=['short', 'medium', 'long'])
df.groupby('trip_distance_group', observed=False)['passenger_count'].mean().round(2).sort_values(ascending=False)

trip_distance_group
medium    1.59
long      1.59
short     1.56
Name: passenger_count, dtype: float64

Create a single data frame containing rides from both January 2019 and January 2020, with a column year indicating which year the ride comes from. Use
`groupby`  to compare the average cost of a taxi in January from each of these two
years.

In [113]:
jan_2019_filename = './data/nyc_taxi_2019-01.csv'
jan_2020_filename = './data/nyc_taxi_2020-01.csv'

In [114]:
jan_2019_df = pd.read_csv(jan_2019_filename,
                usecols=['passenger_count',
                         'trip_distance', 'total_amount'])
jan_2019_df['year'] = 2019
jan_2020_df = pd.read_csv(jan_2020_filename,
                usecols=['passenger_count',
                         'trip_distance', 'total_amount'])
jan_2020_df['year'] = 2020

In [115]:
df = pd.concat([jan_2019_df, jan_2020_df])

In [118]:
df.groupby('year')['total_amount'].mean().round(2)

year
2019    15.68
2020    18.66
Name: total_amount, dtype: float64

Create a two-level grouping, first by year and then by `passenger_count`.

In [121]:
df.groupby(['year', 'passenger_count'])['total_amount'].mean().round(2)

year  passenger_count
2019  0.0                18.66
      1.0                15.61
      2.0                15.83
      3.0                15.60
      4.0                15.65
      5.0                15.55
      6.0                15.44
      7.0                48.28
      8.0                64.11
      9.0                31.09
2020  0.0                18.06
      1.0                18.34
      2.0                19.05
      3.0                18.74
      4.0                19.13
      5.0                18.23
      6.0                18.37
      7.0                71.14
      8.0                58.20
      9.0                81.24
Name: total_amount, dtype: float64

Use `corr` and then sort_values to find which columns have the highest correlation.

In [124]:
df.corr().sort_values('passenger_count').round(4)

                 passenger_count  trip_distance  total_amount    year
year                     -0.0216         0.0011        0.0077  1.0000
total_amount             -0.0001         0.0043        1.0000  0.0077
trip_distance             0.0090         1.0000        0.0043  0.0011
passenger_count           1.0000         0.0090       -0.0001 -0.0216

# 31

Load the `oecd_tourism.csv` file into a data frame. Use only the columns `LOCATION`, `SUBJECT`, `TIME`, and `Value`.

In [125]:
tourism_filename = './data/oecd_tourism.csv'
tourism_df = pd.read_csv(tourism_filename,
                        usecols=['LOCATION', 'SUBJECT', 'TIME', 'Value'])

tourism_df.head()

  LOCATION  SUBJECT  TIME    Value
0      AUS  INT_REC  2008  31159.8
1      AUS  INT_REC  2009  29980.7
2      AUS  INT_REC  2010  35165.5
3      AUS  INT_REC  2011  38710.1
4      AUS  INT_REC  2012  38003.7

Find the five countries that received the greatest amount of tourist dollars, on
average, across years in the data set.

In [128]:
(
    tourism_df
    .loc[tourism_df['SUBJECT'] == 'INT_REC']
    .groupby('LOCATION')['Value']
    .mean()
    .sort_values(ascending=False)
    .head()
    .round(2)
)

LOCATION
USA    201613.50
ESP     69655.82
FRA     65063.34
DEU     53408.57
GBR     51752.09
Name: Value, dtype: float64

Find the five countries whose citizens spent the least amount of tourist dollars,
on average, across years in the data set.

In [129]:
(
    tourism_df
    .loc[tourism_df['SUBJECT'] == 'INT-EXP']
    .groupby('LOCATION')['Value']
    .mean()
    .sort_values()
    .head()
    .round(2)
)

LOCATION
MLT     387.80
CRI     867.08
LVA     919.55
ISL    1072.82
HRV    1115.63
Name: Value, dtype: float64

In [131]:
locations_filename = './data/oecd_locations.csv'
locations_df = pd.read_csv(locations_filename,
                           header=None,
                           names=['LOCATION', 'NAME'],
                           index_col='LOCATION')

Load the `oecd_locations.csv` file into a data frame. Use the `LOCATION` column as the index

In [132]:
fullname_df = locations_df.join(tourism_df.set_index('LOCATION'))
fullname_df.head()

               NAME  SUBJECT  TIME    Value
LOCATION
AUS       Australia  INT_REC  2008  31159.8
AUS       Australia  INT_REC  2009  29980.7
AUS       Australia  INT_REC  2010  35165.5
AUS       Australia  INT_REC  2011  38710.1
AUS       Australia  INT_REC  2012  38003.7

Join the two data frames, `tourism_df` and `locations_df`, using the `LOCATION` column as the index. What is the name of the country with the most tourist dollars received?

In [136]:
(
    fullname_df
    .loc[fullname_df['SUBJECT'] == 'INT_REC']
    .groupby('NAME')['Value']
    .mean()
    .sort_values(ascending=False)
    .head()
    .round(2)
)

NAME
United States     201613.50
France             65063.34
Germany            53408.57
United Kingdom     51752.09
Italy              44930.21
Name: Value, dtype: float64

What is the name of the country with the least amount of tourist dollars spent?

In [135]:
(
    fullname_df
    .loc[fullname_df['SUBJECT'] == 'INT-EXP']
    .groupby('NAME')['Value']
    .mean()
    .sort_values()
    .head()
    .round(2)
)

NAME
Hungary     2918.39
Finland     5877.08
Israel      6726.52
Denmark    11326.17
Austria    11934.56
Name: Value, dtype: float64

What happens if you perform the join in the other direction? That is, what if
you invoke join on `tourism_df`, passing it an argument of `locations_df`? Do
you get the same result?

In [143]:
emanlluf_df = tourism_df.set_index('LOCATION').join(locations_df)
emanlluf_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1234 entries, AUS to SRB
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SUBJECT  1234 non-null   object
 1   TIME     1234 non-null   int64
 2   Value    1234 non-null   float64
 3   NAME     364 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 48.2+ KB

Get the mean tourism income per year rather than by country. Do you see any
evidence of less tourism income during the time of the Great Recession, which
started in 2008?

In [178]:
(
    fullname_df
    .loc[fullname_df['SUBJECT'] == 'INT_REC']
    .groupby('TIME')['Value']
    .mean()
    .sort_values(ascending=False)
    .round(2)
)

TIME
2019    62786.62
2018    43185.85
2017    40326.70
2014    40043.33
2016    39483.59
2015    38912.70
2013    37996.20
2012    35628.63
2011    34299.97
2008    31757.07
2010    30949.52
2009    28505.89
Name: Value, dtype: float64

Reset the index on `locations_df` such that it has a (default) numeric index and
two columns (`LOCATION` and `NAME`). Now run join on `locations_df`, specifying
that you want to use the `LOCATION` column on the caller rather than its index. (The
data frame passed as an argument to join will always be joined on its index.)

In [179]:
tourism_df = tourism_df.set_index('LOCATION')
locations_df.join(tourism_df, on='LOCATION')

               NAME  SUBJECT  TIME    Value
LOCATION
AUS       Australia  INT_REC  2008  31159.8
AUS       Australia  INT_REC  2009  29980.7
AUS       Australia  INT_REC  2010  35165.5
AUS       Australia  INT_REC  2011  38710.1
AUS       Australia  INT_REC  2012  38003.7
...             ...      ...   ...      ...
ISR          Israel  INT-EXP  2015   7507.0
ISR          Israel  INT-EXP  2016   8210.3
ISR          Israel  INT-EXP  2017   8986.0
ISR          Israel  INT-EXP  2018   9974.7
ISR          Israel  INT-EXP  2019  10389.5

[364 rows x 4 columns]